# .github/workflows/node-jekyll-pages.yml
name: Build Node + Deploy Jekyll to GitHub Pages

# --------------------------------------------------------------
# Triggers
# --------------------------------------------------------------
on:
  push:
    branches: [ "master" ]          # run on pushes to the default branch
  pull_request:
    branches: [ "master" ]          # also run on PRs (optional)
  workflow_dispatch:                # manual trigger from the Actions UI

# --------------------------------------------------------------
# Permissions (required for Pages deployment)
# --------------------------------------------------------------
permissions:
  contents: read
  pages: write          # needed for actions/deploy-pages
  id-token: write      # needed for OIDC token when configuring Pages

# --------------------------------------------------------------
# Concurrency – keep only the latest run alive
# --------------------------------------------------------------
concurrency:
  group: "pages-deploy"
  cancel-in-progress: true   # cancel older runs when a new one starts

# --------------------------------------------------------------
# Jobs
# --------------------------------------------------------------

# -----------------------------------------------------------------
# 1️⃣  Node.js build – produces the `dist/` folder
# -----------------------------------------------------------------
build:
  runs-on: ubuntu-latest
  outputs:
    artifact-name: node-dist   # expose the artifact name to later jobs
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x            # stable LTS (adjust if you really need 22.x)
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build --if-present

    # -------------------------------------------------------------
    # OPTIONAL: run tests here
    # -------------------------------------------------------------
    # - name: Run tests
    #   run: npm test

    - name: Upload build artifact (dist/)
      uses: actions/upload-artifact@v4
      with:
        name: node-dist
        path: dist/
        retention-days: 7   # keep for a week (adjust as needed)

# -----------------------------------------------------------------
# 2️⃣  Jekyll build – consumes the artifact from the previous job
# -----------------------------------------------------------------
jekyll:
  needs: build                     # wait until the Node build finishes
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    # -------------------------------------------------------------
    # Pull the artifact that the `build` job just uploaded
    # -------------------------------------------------------------
    - name: Download Node build artifact
      uses: actions/download-artifact@v4
      with:
        name: node-dist
        path: dist               # places the files under ./dist

    - name: List downloaded files (debug)
      run: ls -R dist

    # -------------------------------------------------------------
    # Configure the Pages environment (needed for the Jekyll action)
    # -------------------------------------------------------------
    - name: Set up GitHub Pages
      uses: actions/configure-pages@v4

    # -------------------------------------------------------------
    # Run Jekyll against the downloaded `dist/` folder
    # -------------------------------------------------------------
    - name: Build site with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./dist          # Jekyll reads from here
        destination: ./_site    # output folder

    # -------------------------------------------------------------
    # Package the generated site for Pages deployment
    # -------------------------------------------------------------
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_site           # this is what deploy-pages expects

# -----------------------------------------------------------------
# 3️⃣  Deploy to GitHub Pages
# -----------------------------------------------------------------
deploy:
  needs: jekyll                    # only runs after the Jekyll job succeeds
  runs-on: ubuntu-latest
  environment:
    name: github-pages
    url: ${{ steps.deploy.outputs.page_url }}
  steps:
    - name: Deploy to GitHub Pages
      id: deploy
      uses: actions/deploy-pages@v4
